export default [
  {
    playerId: "3582",
    position: "RB",
    displayName: "Saquon Barkley",
    fname: "Saquon",
    lname: "Barkley",
    team: "NYG",
    byeWeek: "11",
    standDev: "0.416",
    nerdRank: "1.056",
    positionRank: "1",
    overallRank: 1
  },
  {
    playerId: "3037",
    position: "RB",
    displayName: "Ezekiel Elliott",
    fname: "Ezekiel",
    lname: "Elliott",
    team: "DAL",
    byeWeek: "8",
    standDev: "0.705",
    nerdRank: "2.050",
    positionRank: "2",
    overallRank: 2
  },
  {
    playerId: "3379",
    position: "RB",
    displayName: "Christian McCaffrey",
    fname: "Christian",
    lname: "McCaffrey",
    team: "CAR",
    byeWeek: "7",
    standDev: "0.731",
    nerdRank: "3.119",
    positionRank: "3",
    overallRank: 3
  },
  {
    playerId: "3384",
    position: "RB",
    displayName: "Alvin Kamara",
    fname: "Alvin",
    lname: "Kamara",
    team: "NO",
    byeWeek: "9",
    standDev: "0.533",
    nerdRank: "3.801",
    positionRank: "4",
    overallRank: 4
  },
  {
    playerId: "2338",
    position: "WR",
    displayName: "DeAndre Hopkins",
    fname: "DeAndre",
    lname: "Hopkins",
    team: "HOU",
    byeWeek: "10",
    standDev: "0.229",
    nerdRank: "6.035",
    positionRank: "1",
    overallRank: 5
  },
  {
    playerId: "2759",
    position: "RB",
    displayName: "Melvin Gordon",
    fname: "Melvin",
    lname: "Gordon",
    team: "LAC",
    byeWeek: "12",
    standDev: "0.870",
    nerdRank: "6.143",
    positionRank: "5",
    overallRank: 6
  },
  {
    playerId: "2596",
    position: "WR",
    displayName: "Davante Adams",
    fname: "Davante",
    lname: "Adams",
    team: "GB",
    byeWeek: "11",
    standDev: "1.066",
    nerdRank: "9.331",
    positionRank: "2",
    overallRank: 7
  },
  {
    playerId: "1446",
    position: "WR",
    displayName: "Julio Jones",
    fname: "Julio",
    lname: "Jones",
    team: "ATL",
    byeWeek: "9",
    standDev: "1.740",
    nerdRank: "11.512",
    positionRank: "3",
    overallRank: 8
  },
  {
    playerId: "2771",
    position: "RB",
    displayName: "Todd Gurley",
    fname: "Todd",
    lname: "Gurley",
    team: "LAR",
    byeWeek: "9",
    standDev: "2.114",
    nerdRank: "7.440",
    positionRank: "6",
    overallRank: 9
  },
  {
    playerId: "3119",
    position: "WR",
    displayName: "Michael Thomas",
    fname: "Michael",
    lname: "Thomas",
    team: "NO",
    byeWeek: "9",
    standDev: "1.083",
    nerdRank: "12.310",
    positionRank: "4",
    overallRank: 10
  },
  {
    playerId : "2760",
    position : "RB",
    displayName: "David Johnson",
    fname: "David",
    lname: "Johnson",
    team : "ARI",
    byeWeek: "12",
    standDev : "1.663",
    nerdRank : "10.829",
    positionRank : "7",
    overallRank: 11
  },
  {
    playerId : "2198",
    position : "TE",
    displayName: "Travis Kelce",
    fname: "Travis",
    lname: "Kelce",
    team : "KC",
    byeWeek: "12",
    standDev : "0.000",
    nerdRank : "15.844",
    positionRank : "1",
    overallRank : 1  
  },
  {
    playerId: "2465",
    position: "WR",
    displayName: "Odell Beckham Jr.",
    fname: "Odell",
    lname: "Beckham Jr.",
    team: "CLE",
    byeWeek: "7",
    standDev: "1.239",
    nerdRank: "13.611",
    positionRank: "5",
    overallRank: 13
  },
  {
    playerId: "2289",
    position: "RB",
    displayName: "Le'Veon Bell",
    fname: "Le'Veon",
    lname: "Bell",
    team: "NYJ",
    byeWeek: "4",
    standDev: "0.896",
    nerdRank: "9.763",
    positionRank: "8",
    overallRank: 14
  },
  {
    playerId: "3339",
    position: "RB",
    displayName: "James Conner",
    fname: "James",
    lname: "Conner",
    team: "PIT",
    byeWeek: "7",
    standDev: "1.239",
    nerdRank: "11.586",
    positionRank: "9",
    overallRank: 15
  },
  {
    playerId: "3340",
    position: "WR",
    displayName: "JuJu Smith-Schuster",
    fname: "JuJu",
    lname: "Smith-Schuster",
    team: "PIT",
    byeWeek: "7",
    standDev: "1.333",
    nerdRank: "18.437",
    positionRank: "6",
    overallRank: 16
  },
  {
    playerId: "3329",
    position: "RB",
    displayName: "Joe Mixon",
    fname: "Joe",
    lname: "Mixon",
    team: "CIN",
    byeWeek: "9",
    standDev: "1.112",
    nerdRank: "15.311",
    positionRank: "10",
    overallRank: 17
  },
  {
    playerId: "1142",
    position: "WR",
    displayName: "Antonio Brown",
    fname: "Antonio",
    lname: "Brown",
    team: "OAK",
    byeWeek: "6",
    standDev: "1.615",
    nerdRank: "17.765",
    positionRank: "7",
    overallRank: 18
  },
  {
    playerId: "3600",
    position: "RB",
    displayName: "Nick Chubb",
    fname: "Nick",
    lname: "Chubb",
    team: "CLE",
    byeWeek: "7",
    standDev: "1.615",
    nerdRank: "18.057",
    positionRank: "11",
    overallRank: 19
  },
  {
    playerId: "3324",
    position: "TE",
    displayName: "George Kittle",
    fname: "George",
    lname: "Kittle",
    team: "SF",
    byeWeek: "4",
    standDev: "0.601",
    nerdRank: "26.392",
    positionRank: "2",
    overallRank: 20
  }
]